# GitHub Pages Jekyll Configuration
title: "Base64 圖片解碼與像素分析工具"
description: "一個簡單易用的 Base64 圖片解碼工具，支援圖片顯示與詳細的像素分析功能"
url: "https://qqjckimo.github.io"
baseurl: "/base64Decoder"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages specific settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: zh-TW
author: Jason Chen

# Social settings
github_username: qqjckimo

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .git/
  - node_modules/
  - vendor/

# Include files
include:
  - index.html